<?php
$sql = array();
$sql []= "CREATE TABLE `pet_". $prefix ."_blood_import` ( `id` int(11) NOT NULL AUTO_INCREMENT, `time` int(11) NOT NULL, `price` int(11) NOT NULL, `number1` int(11) NOT NULL, `note` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL, `doctor` int(11) NOT NULL DEFAULT '0', `number2` int(11) NOT NULL, `number3` int(11) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_blood_row` ( `id` int(11) NOT NULL AUTO_INCREMENT, `time` int(11) NOT NULL, `number` int(11) NOT NULL, `start` int(11) NOT NULL, `end` int(11) NOT NULL, `doctor` int(11) NOT NULL, `target` int(11) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=171 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_customer` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(50) NOT NULL, `phone` varchar(20) NOT NULL, `address` text NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=11738 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_disease` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_doctor` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(50) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_expire` ( `id` int(11) NOT NULL AUTO_INCREMENT, `rid` int(11) NOT NULL, `number` int(11) NOT NULL DEFAULT '0', `exp_time` int(11) NOT NULL, `update_time` int(11) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=193 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_kaizen` ( `id` int(11) NOT NULL AUTO_INCREMENT, `userid` int(11) NOT NULL, `problem` varchar(500) NOT NULL, `solution` varchar(500) NOT NULL, `result` varchar(500) NOT NULL, `post_time` int(11) NOT NULL, `edit_time` int(11) NOT NULL, `active` int(11) NOT NULL DEFAULT '1', `done` int(11) NOT NULL DEFAULT '0', PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=48 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_notify` ( `id` int(11) NOT NULL AUTO_INCREMENT, `userid` int(11) NOT NULL, `action` int(11) NOT NULL, `workid` int(11) NOT NULL, `module` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `time` int(11) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=141 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_notify_last` ( `id` int(11) NOT NULL AUTO_INCREMENT, `module` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `time` int(11) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_notify_read` ( `id` int(11) NOT NULL AUTO_INCREMENT, `userid` int(11) NOT NULL, `module` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `time` int(11) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_penety` ( `id` int(11) NOT NULL AUTO_INCREMENT, `userid` int(11) NOT NULL, `time` int(11) NOT NULL, `type` int(11) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=471 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_pet` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, `customerid` int(11) NOT NULL, `age` int(11) NOT NULL, `weight` int(11) NOT NULL, `species` int(11) NOT NULL, `status` int(11) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=4427 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_remind` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL, `value` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `active` int(11) NOT NULL DEFAULT '0', `rate` int(11) NOT NULL DEFAULT '0', PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=54 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_ride` ( `id` int(11) NOT NULL AUTO_INCREMENT, `type` int(11) NOT NULL, `driver_id` int(11) NOT NULL, `doctor_id` int(11) NOT NULL, `customer_id` int(11) NOT NULL, `amount` varchar(20) NOT NULL, `clock_from` decimal(11,1) NOT NULL, `clock_to` decimal(11,1) NOT NULL, `destination` varchar(200) NOT NULL, `note` varchar(200) NOT NULL, `time` int(11) NOT NULL, `price` text NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=1532 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_row` ( `id` int(11) NOT NULL AUTO_INCREMENT, `type` int(11) NOT NULL, `user_id` int(11) NOT NULL, `time` int(11) NOT NULL, `reg_time` int(11) NOT NULL DEFAULT '0', PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=5478 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_spa` ( `id` int(11) NOT NULL AUTO_INCREMENT, `doctorid` int(11) NOT NULL, `doctor` int(11) DEFAULT '1', `customerid` int(11) NOT NULL, `weight` int(11) NOT NULL, `note` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, `wash_dog` int(11) NOT NULL DEFAULT '0', `wash_cat` int(11) NOT NULL DEFAULT '0', `wash_white` int(11) NOT NULL DEFAULT '0', `cut_fur` int(11) NOT NULL DEFAULT '0', `shave_foot` int(11) NOT NULL DEFAULT '0', `shave_fur` int(11) NOT NULL DEFAULT '0', `cut_claw` int(11) NOT NULL DEFAULT '0', `cut_curly` int(11) NOT NULL DEFAULT '0', `wash_ear` int(11) NOT NULL DEFAULT '0', `wash_mouth` int(11) NOT NULL DEFAULT '0', `paint_footear` int(11) NOT NULL DEFAULT '0', `paint_all` int(11) NOT NULL DEFAULT '0', `pin_ear` int(11) NOT NULL DEFAULT '0', `cut_ear` int(11) NOT NULL DEFAULT '0', `dismell` int(11) NOT NULL DEFAULT '0', `time` int(11) NOT NULL DEFAULT '0', `done` int(11) NOT NULL DEFAULT '0', `payment` int(11) NOT NULL DEFAULT '0', `image` varchar(500) NOT NULL DEFAULT '', `type` varchar(256) NOT NULL DEFAULT '', PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=3824 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_spa_type` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_user` ( `id` int(11) NOT NULL AUTO_INCREMENT, `userid` int(11) NOT NULL, `manager` int(11) NOT NULL DEFAULT '0', `except` int(11) NOT NULL DEFAULT '0', `daily` int(11) NOT NULL DEFAULT '0', `kaizen` int(11) NOT NULL DEFAULT '0', PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_usg2` ( `id` int(11) NOT NULL AUTO_INCREMENT, `petid` int(11) NOT NULL, `doctorid` int(11) NOT NULL, `usgtime` int(11) NOT NULL, `expecttime` int(11) NOT NULL, `expectnumber` int(11) NOT NULL, `birthtime` int(11) NOT NULL DEFAULT '0', `number` int(11) NOT NULL DEFAULT '0', `vaccinetime` int(11) NOT NULL, `image` varchar(2048) COLLATE utf8mb4_unicode_ci NOT NULL, `status` int(11) NOT NULL, `note` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL, `time` int(11) NOT NULL, PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=119 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_vaccine` ( `id` int(11) NOT NULL AUTO_INCREMENT, `petid` int(11) NOT NULL, `diseaseid` int(11) NOT NULL, `cometime` int(11) NOT NULL, `calltime` int(11) NOT NULL, `note` text NOT NULL, `status` tinyint(4) NOT NULL, `recall` int(11) NOT NULL, `doctorid` int(11) NOT NULL, `ctime` int(11) DEFAULT '0', PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=7777 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_work` ( `id` int(11) NOT NULL AUTO_INCREMENT, `cometime` int(11) NOT NULL, `calltime` int(11) NOT NULL, `last_time` int(11) NOT NULL, `post_user` int(11) NOT NULL, `edit_user` int(11) NOT NULL, `userid` int(11) NOT NULL, `depart` int(11) NOT NULL, `customer` int(11) NOT NULL, `content` text COLLATE utf8mb4_unicode_ci NOT NULL, `process` int(11) NOT NULL DEFAULT '0', `confirm` int(11) NOT NULL DEFAULT '0', `review` int(11) NOT NULL DEFAULT '0', `note` text COLLATE utf8mb4_unicode_ci NOT NULL, `active` int(11) NOT NULL DEFAULT '1', `image` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '', PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=67 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_xray` ( `id` int(11) NOT NULL AUTO_INCREMENT, `petid` int(11) NOT NULL, `doctorid` int(11) NOT NULL, `cometime` int(11) NOT NULL, `insult` int(11) NOT NULL DEFAULT '0', `ctime` int(11) NOT NULL DEFAULT '0', PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;";
$sql []= "CREATE TABLE `pet_". $prefix ."_xray_row` ( `id` int(11) NOT NULL AUTO_INCREMENT, `xrayid` int(11) NOT NULL, `temperate` varchar(200) NOT NULL, `eye` varchar(200) NOT NULL, `other` varchar(500) NOT NULL, `image` varchar(2000) NOT NULL, `time` int(11) NOT NULL, `treating` varchar(500) NOT NULL, `condition` int(11) NOT NULL DEFAULT '0', `doctor` int(11) NOT NULL DEFAULT '0', PRIMARY KEY (`id`)  ) ENGINE=MyISAM AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;";
foreach ($sql as $string) {
  try {
    $db->query($string);
  }
  catch(Exception $e) {
    // lỗi thì bỏ qua
  }
}